### ISSUE TITLE
Default sound makes the phone vibrate on silent notifications

### ISSUE THREAD

**Issue by igorcferreira** [FutureWorkshops/notifiable-apns-grocer#1]
The code is applying 'default' as a sound payload. For a silent notification, this causes the phone to vibrate, or sound.

https://github.com/FutureWorkshops/notifiable-apns-grocer/blob/0e855ced44bdafc7b0bf18bae69627224e9c5bb5/lib/notifiable/apns/grocer/stream.rb#L91

**Comment by FWMatt** [comment]
Resolved with commit to notifiable-apns-apnotic
